# Veskere podporovane parametry jsou k vyhledani v oficialni dokumentaci:
# https://docs.spring.io/spring-boot/docs/current/reference/html/application-properties.html

server:
  port: 9000
  http2:
    enabled: true
  servlet:
    context-path: /api/v1

spring:
  data:
    rest:
      base-path: /api/v1

  datasource:
    url: jdbc:postgresql://localhost:5432/nnpia
    username: nnpia
    password: nnpia

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
      org:
        hibernate:
          dialect: PostgreSQL81Dialect

  graphql:
    path: /graphql
    graphiql:
      enabled: true
      path: /graphiql

