# Veskere podporovane parametry jsou k vyhledani v oficialni dokumentaci:
# https://docs.spring.io/spring-boot/docs/current/reference/html/application-properties.html

server:
  port: 9000
  http2:
    enabled: true
  servlet:
    context-path: /api/v2

spring:
  data:
    rest:
      base-path: /api/v2
